import type { Client, User, Service, Appointment, Tenant } from "@/types";

export const mockTenant: Tenant = {
  id: "t_01",
  name: "Salão Bella Donna",
  slug: "bella-donna",
  plan: "PRO",
  trialEndsAt: null,
  stripeCustomerId: "cus_mock",
  stripeSubscriptionId: "sub_mock",
  stripeCurrentPeriodEnd: new Date("2026-06-30"),
  createdAt: new Date("2025-01-10"),
};

export const mockUsers: User[] = [
  {
    id: "u_01",
    tenantId: "t_01",
    email: "ana@belladonna.com",
    name: "Ana Souza",
    role: "OWNER",
    avatarUrl: null,
    createdAt: new Date("2025-01-10"),
  },
  {
    id: "u_02",
    tenantId: "t_01",
    email: "carla@belladonna.com",
    name: "Carla Mendes",
    role: "PROFESSIONAL",
    avatarUrl: null,
    createdAt: new Date("2025-01-12"),
  },
  {
    id: "u_03",
    tenantId: "t_01",
    email: "julia@belladonna.com",
    name: "Júlia Ferreira",
    role: "PROFESSIONAL",
    avatarUrl: null,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "u_04",
    tenantId: "t_01",
    email: "marina@belladonna.com",
    name: "Marina Costa",
    role: "RECEPTIONIST",
    avatarUrl: null,
    createdAt: new Date("2025-03-15"),
  },
];

export const mockClients: Client[] = [
  {
    id: "c_01",
    tenantId: "t_01",
    name: "Fernanda Lima",
    phone: "(11) 99876-5432",
    email: "fernanda@email.com",
    birthDate: new Date("1990-05-15"),
    status: "ACTIVE",
    createdAt: new Date("2025-02-01"),
    hairColor: "Loiro mel",
    skinTone: "Clara",
    nailPolish: "Rosa nude",
    allergies: null,
    notes: "Prefere horários pela manhã",
  },
  {
    id: "c_02",
    tenantId: "t_01",
    name: "Beatriz Oliveira",
    phone: "(11) 98765-4321",
    email: "bia@email.com",
    birthDate: new Date("1985-11-22"),
    status: "VIP",
    createdAt: new Date("2025-01-15"),
    hairColor: "Castanho escuro",
    skinTone: "Morena",
    nailPolish: "Vermelho",
    allergies: "Amônia",
    notes: "Cliente VIP, agenda com Carla sempre",
  },
  {
    id: "c_03",
    tenantId: "t_01",
    name: "Camila Rocha",
    phone: "(11) 97654-3210",
    email: null,
    birthDate: new Date("1995-03-08"),
    status: "AT_RISK",
    createdAt: new Date("2025-02-20"),
    hairColor: "Preto natural",
    skinTone: "Morena clara",
    nailPolish: null,
    allergies: null,
    notes: null,
  },
  {
    id: "c_04",
    tenantId: "t_01",
    name: "Larissa Santos",
    phone: "(11) 96543-2109",
    email: "larissa@email.com",
    birthDate: new Date("1992-07-30"),
    status: "INACTIVE",
    createdAt: new Date("2025-01-20"),
    hairColor: "Ruivo",
    skinTone: "Clara",
    nailPolish: "Lilás",
    allergies: "Peroxide",
    notes: "Não ligar depois das 19h",
  },
  {
    id: "c_05",
    tenantId: "t_01",
    name: "Juliana Costa",
    phone: "(11) 95432-1098",
    email: "jucosta@email.com",
    birthDate: new Date("1988-12-01"),
    status: "ACTIVE",
    createdAt: new Date("2025-03-01"),
    hairColor: "Loiro platinado",
    skinTone: "Clara",
    nailPolish: "Branco",
    allergies: null,
    notes: null,
  },
  {
    id: "c_06",
    tenantId: "t_01",
    name: "Priscila Alves",
    phone: "(11) 94321-0987",
    email: null,
    birthDate: null,
    status: "AT_RISK",
    createdAt: new Date("2025-02-10"),
    hairColor: "Castanho claro",
    skinTone: "Parda",
    nailPolish: "Coral",
    allergies: null,
    notes: null,
  },
  {
    id: "c_07",
    tenantId: "t_01",
    name: "Rafaela Nunes",
    phone: "(11) 93210-9876",
    email: "rafa@email.com",
    birthDate: new Date("1997-09-14"),
    status: "ACTIVE",
    createdAt: new Date("2025-04-05"),
    hairColor: "Mel",
    skinTone: "Morena",
    nailPolish: "Esmalte gel",
    allergies: null,
    notes: "Adora hidratação capilar",
  },
  {
    id: "c_08",
    tenantId: "t_01",
    name: "Tatiana Braga",
    phone: "(11) 92109-8765",
    email: "tati@email.com",
    birthDate: new Date("1983-04-25"),
    status: "VIP",
    createdAt: new Date("2025-01-05"),
    hairColor: "Loiro escuro",
    skinTone: "Clara",
    nailPolish: "Nude",
    allergies: null,
    notes: "Traz a filha junto às vezes",
  },
  {
    id: "c_09",
    tenantId: "t_01",
    name: "Vanessa Moura",
    phone: "(11) 91098-7654",
    email: null,
    birthDate: new Date("2000-01-18"),
    status: "INACTIVE",
    createdAt: new Date("2025-02-28"),
    hairColor: "Preto tingido",
    skinTone: "Morena escura",
    nailPolish: "Preto",
    allergies: "Formol",
    notes: null,
  },
  {
    id: "c_10",
    tenantId: "t_01",
    name: "Isabela Carvalho",
    phone: "(11) 90987-6543",
    email: "isa@email.com",
    birthDate: new Date("1993-06-22"),
    status: "ACTIVE",
    createdAt: new Date("2025-03-20"),
    hairColor: "Ombré loiro",
    skinTone: "Clara",
    nailPolish: "Rosa choque",
    allergies: null,
    notes: null,
  },
  {
    id: "c_11",
    tenantId: "t_01",
    name: "Débora Lima",
    phone: "(21) 99876-1234",
    email: "debora@email.com",
    birthDate: new Date("1991-08-10"),
    status: "ACTIVE",
    createdAt: new Date("2025-04-01"),
    hairColor: "Castanho",
    skinTone: "Morena",
    nailPolish: null,
    allergies: null,
    notes: "Prefere Júlia como profissional",
  },
  {
    id: "c_12",
    tenantId: "t_01",
    name: "Monique Teixeira",
    phone: "(21) 98765-2345",
    email: null,
    birthDate: null,
    status: "AT_RISK",
    createdAt: new Date("2025-03-10"),
    hairColor: "Platinado",
    skinTone: "Clara",
    nailPolish: "Transparente",
    allergies: null,
    notes: null,
  },
];

export const mockServices: Service[] = [
  {
    id: "s_01",
    tenantId: "t_01",
    name: "Corte feminino",
    returnDays: 45,
    price: 80,
    durationMinutes: 60,
    active: true,
  },
  {
    id: "s_02",
    tenantId: "t_01",
    name: "Coloração",
    returnDays: 30,
    price: 180,
    durationMinutes: 120,
    active: true,
  },
  {
    id: "s_03",
    tenantId: "t_01",
    name: "Hidratação capilar",
    returnDays: 21,
    price: 90,
    durationMinutes: 60,
    active: true,
  },
  {
    id: "s_04",
    tenantId: "t_01",
    name: "Manicure",
    returnDays: 14,
    price: 45,
    durationMinutes: 45,
    active: true,
  },
  {
    id: "s_05",
    tenantId: "t_01",
    name: "Pedicure",
    returnDays: 14,
    price: 55,
    durationMinutes: 60,
    active: true,
  },
  {
    id: "s_06",
    tenantId: "t_01",
    name: "Escova progressiva",
    returnDays: 90,
    price: 250,
    durationMinutes: 180,
    active: true,
  },
  {
    id: "s_07",
    tenantId: "t_01",
    name: "Design de sobrancelha",
    returnDays: 30,
    price: 35,
    durationMinutes: 30,
    active: true,
  },
  {
    id: "s_08",
    tenantId: "t_01",
    name: "Cauterização",
    returnDays: 60,
    price: 130,
    durationMinutes: 90,
    active: false,
  },
];

const today = new Date();
const daysAgo = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d;
};

export const mockAppointments: Appointment[] = [
  {
    id: "a_01",
    tenantId: "t_01",
    clientId: "c_01",
    professionalId: "u_02",
    serviceId: "s_01",
    date: daysAgo(5),
    price: 80,
    notes: null,
    createdAt: daysAgo(5),
  },
  {
    id: "a_02",
    tenantId: "t_01",
    clientId: "c_02",
    professionalId: "u_02",
    serviceId: "s_02",
    date: daysAgo(3),
    price: 180,
    notes: "Retoque nas raízes",
    createdAt: daysAgo(3),
  },
  {
    id: "a_03",
    tenantId: "t_01",
    clientId: "c_02",
    professionalId: "u_02",
    serviceId: "s_04",
    date: daysAgo(3),
    price: 45,
    notes: null,
    createdAt: daysAgo(3),
  },
  {
    id: "a_04",
    tenantId: "t_01",
    clientId: "c_05",
    professionalId: "u_03",
    serviceId: "s_06",
    date: daysAgo(7),
    price: 250,
    notes: null,
    createdAt: daysAgo(7),
  },
  {
    id: "a_05",
    tenantId: "t_01",
    clientId: "c_07",
    professionalId: "u_03",
    serviceId: "s_03",
    date: daysAgo(2),
    price: 90,
    notes: null,
    createdAt: daysAgo(2),
  },
  {
    id: "a_06",
    tenantId: "t_01",
    clientId: "c_08",
    professionalId: "u_02",
    serviceId: "s_02",
    date: daysAgo(1),
    price: 180,
    notes: "Mechas balayage",
    createdAt: daysAgo(1),
  },
  {
    id: "a_07",
    tenantId: "t_01",
    clientId: "c_10",
    professionalId: "u_03",
    serviceId: "s_01",
    date: daysAgo(4),
    price: 80,
    notes: null,
    createdAt: daysAgo(4),
  },
  {
    id: "a_08",
    tenantId: "t_01",
    clientId: "c_11",
    professionalId: "u_03",
    serviceId: "s_07",
    date: daysAgo(6),
    price: 35,
    notes: null,
    createdAt: daysAgo(6),
  },
  {
    id: "a_09",
    tenantId: "t_01",
    clientId: "c_01",
    professionalId: "u_02",
    serviceId: "s_04",
    date: daysAgo(10),
    price: 45,
    notes: null,
    createdAt: daysAgo(10),
  },
  {
    id: "a_10",
    tenantId: "t_01",
    clientId: "c_08",
    professionalId: "u_02",
    serviceId: "s_04",
    date: daysAgo(8),
    price: 45,
    notes: null,
    createdAt: daysAgo(8),
  },
  {
    id: "a_11",
    tenantId: "t_01",
    clientId: "c_03",
    professionalId: "u_03",
    serviceId: "s_01",
    date: daysAgo(40),
    price: 80,
    notes: null,
    createdAt: daysAgo(40),
  },
  {
    id: "a_12",
    tenantId: "t_01",
    clientId: "c_06",
    professionalId: "u_02",
    serviceId: "s_03",
    date: daysAgo(35),
    price: 90,
    notes: null,
    createdAt: daysAgo(35),
  },
  {
    id: "a_13",
    tenantId: "t_01",
    clientId: "c_04",
    professionalId: "u_03",
    serviceId: "s_02",
    date: daysAgo(90),
    price: 180,
    notes: null,
    createdAt: daysAgo(90),
  },
  {
    id: "a_14",
    tenantId: "t_01",
    clientId: "c_09",
    professionalId: "u_02",
    serviceId: "s_06",
    date: daysAgo(120),
    price: 250,
    notes: null,
    createdAt: daysAgo(120),
  },
  {
    id: "a_15",
    tenantId: "t_01",
    clientId: "c_12",
    professionalId: "u_03",
    serviceId: "s_05",
    date: daysAgo(28),
    price: 55,
    notes: null,
    createdAt: daysAgo(28),
  },
];

// Weekly chart data for last 30 days (appointments per week)
export const mockWeeklyData = [
  { week: "Sem 1", atendimentos: 3 },
  { week: "Sem 2", atendimentos: 5 },
  { week: "Sem 3", atendimentos: 4 },
  { week: "Sem 4", atendimentos: 7 },
];

// Status distribution for pie chart
export const mockStatusData = [
  { name: "Ativas", value: 5, color: "#22c55e" },
  { name: "Em risco", value: 3, color: "#f59e0b" },
  { name: "Inativas", value: 2, color: "#ef4444" },
  { name: "VIP", value: 2, color: "#a855f7" },
];
